Django/Django_실습/20221007_프로젝트-영화 리뷰채널 연결/movpjt/movie/urls.py
from django.urls import path
from . import views 

app_name = 'movie'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('home/', views.home, name='home'),
]

Django/Django_실습/20221007_프로젝트-영화 리뷰채널 연결/movpjt/movpjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movie.urls')),
]

Django/Django_실습/20221007_프로젝트-영화 리뷰채널 연결/movpjt/movie/models.py
from django.db import models


# Create your models here.
class Review(models.Model):
    title = models.CharField(max_length=30) # 리뷰 제목
    content = models.TextField(null=False) # 리뷰 내용
    movie_name = models.CharField(max_length=30) # 영화 이름
    grade = models.DecimalField(max_digits=2, decimal_places=1) # 영화 평점
    created_at = models.DateTimeField(auto_now_add=True) # 리뷰 생성시간
    updated_at = models.DateTimeField(auto_now=True) # 리뷰 수정시간

Django/Django_실습/20221007_프로젝트-영화 리뷰채널 연결/movpjt/movie/forms.py
from django import forms
from .models import Review

 
class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        # 제목, 내용, 이름, 평점을 사용자에게 입력받음 + 유효성 검사
        fields = ['title', 'content', 'movie_name', 'grade']
        widgets = {
            'title' : forms.TextInput(attrs={'class':'form-control'}),
            'content' : forms.Textarea(attrs={'class':'form-control', 'style': 'height: 100px;'}),
            'movie_name' : forms.TextInput(attrs={'class':'form-control'}),
            'grade' : forms.TextInput(attrs={'class':'form-control'}),
        }

Django/Django_실습/20221007_프로젝트-영화 리뷰채널 연결/movpjt/movie/views.py
from django.shortcuts import render, redirect
from .models import Review
from .forms import ReviewForm

# Create your views here.
def index(request):
    reviews = Review.objects.order_by('-pk')
    context = {
        'reviews': reviews
    }
    return render(request, 'movie/index.html', context)

def home(request):
    reviews = Review.objects.order_by('-pk')
    context = {
        'reviews': reviews
    }
    return render(request, 'movie/community.html', context)

def create(request):
    if request.method == 'POST':
        review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            review_form.save()
            return redirect('movie:home')
    else:        
        review_form = ReviewForm()
    context = {
        'review_form': review_form
    }
    return render(request, 'movie/create.html', context=context)

def detail(request, pk):
    review = Review.objects.get(pk=pk)
    context = {
        'review': review
    }
    return render(request, 'movie/detail.html', context)

def delete(request, pk):
    Review.objects.get(pk=pk).delete()
    return redirect('movie:home')

def update(request, pk):
    review = Review.objects.get(pk=pk)
    if request.method == 'POST':
        review_form = ReviewForm(request.POST, instance=review)
        if review_form.is_valid():
            review_form.save()
            return redirect('movie:detail', review.pk)
    else:
        review_form = ReviewForm(instance=review)
    context = {
        'review_form': review_form
    }
    return render(request, 'movie/update.html', context)

Django/Django_실습/20221007_프로젝트-영화 리뷰채널 연결/movpjt/movie/templates/movie/community.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block css %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <style>
    a {
      text-decoration: none;
      color: inherit;
    }
  </style>
{% endblock %}

{% block body %}
  <!-- 게시판 영역 -->
  <section class="mx-5">
    <!-- 게시판 제목 -->
    <div class="text-center my-5 mx-5">
      <a href="{% url 'movie:home' %}">
        <h1>Community</h1>
      </a>
    </div>
    <!-- 게시판 내용 -->
    <div class="row">
      <!-- 테이블 헤더 -->
      <div class="col-lg-3 col-md-12 px-5 mb-3">
        <ul class="list-group">
          <li class="list-group-item">
            <a class="text-decoration-none" href="#">Boxoffice</a>
          </li>
          <li class="list-group-item">
            <a class="text-decoration-none" href="#">Movies</a>
          </li>
          <li class="list-group-item">
            <a class="text-decoration-none" href="#">Genres</a>
          </li>
          <li class="list-group-item">
            <a class="text-decoration-none" href="#">Actors</a>
          </li>
        </ul>
      </div>
      <div class="col-lg-9 col-md-12 px-5 mb-3">
        <!-- 테이블 영역 -->
        <table class="table">
          <!-- 테이블 헤드 -->
          <thead class="table-light">
            <tr>
              <th scope="col">순번</th>
              <th scope="col">리뷰 제목</th>
              <th scope="col">영화 이름</th>
            </tr>
          </thead>
          <!-- 테이블 바디 -->
          <tbody class="table-group-divider">
            {% for review in reviews %}
              <tr>
                <th>{{ review.pk }}</th>
                <th>
                  <a href="{% url 'movie:detail' review.pk %}">{{ review.title }}</a>
                </th>

                <th>{{ review.movie_name }}</th>
              </tr>
            {% endfor %}
          </tbody>
        </table>
        <div class="col-12">
          <a href="{% url 'movie:create' %}">
            <button class="btn btn-outline-primary">리뷰작성</button>
          </a>
        </div>
      </div>
    </div>
  </section>
  <nav class="mt-2 mb-2" aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
      <li class="page-item">
        <a class="page-link" href="#">Previous</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="#">1</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="#">2</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="#">3</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="#">Next</a>
      </li>
    </ul>
  </nav>

{% endblock %}

Django/Django_실습/20221007_프로젝트-영화 리뷰채널 연결/movpjt/movie/templates/movie/create.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block css %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block body %}
  <div class="container mt-3">
    <h1>글쓰기</h1>
    <form action="" method="POST">
      {% csrf_token %}
      {{ review_form.as_p }}
      <button type="submit" class="btn btn-outline-primary">추가</button>
    </form>
  </div>
{% endblock %}

Django/Django_실습/20221007_프로젝트-영화 리뷰채널 연결/movpjt/movie/templates/movie/detail.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block css %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block body %}
  <form class="container mt-3">
    <h1>{{ review.title }}</h1>
    <span>작성시간 :
      {{ review.created_at }}
      | 수정시간 :
      {{ review.updated_at }}</span>
    <div class="mb-3 mt-3">
      <label for="reviewContent" class="form-label">내용</label>
      <textarea name='content' class="form-control" id="reviewContent" rows="3" disabled="disabled" readonly="readonly">{{ review.content }}</textarea>
    </div>
    <div class="mb-3">
      <label for="moviename" class="form-label">영화 제목</label>
      <textarea name='content' class="form-control" id="moviename" rows="3" disabled="disabled" readonly="readonly">{{ review.movie_name }}</textarea>
    </div>
    <div class="mb-3">
      <label for="reviewgrade" class="form-label">평점</label>
      <textarea name='content' class="form-control" id="reviewgrade" rows="3" disabled="disabled" readonly="readonly">{{ review.movie_name }}</textarea>
    </div>

    <div class="row">
      <div class="col">
        <a href="{% url 'movie:update' review.pk %}">
          <button type="button" class="btn btn-outline-primary">리뷰 수정</button>
        </a>

        <a href="{% url 'movie:delete' review.pk %}">
          <button type="button" class="btn btn-outline-danger">리뷰 삭제</button>
        </a>
      </div>
    </div>
  </form>
{% endblock %}

Django/Django_실습/20221007_프로젝트-영화 리뷰채널 연결/movpjt/movie/templates/movie/index.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block css %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block body %}
  <!-- carousel -->
  <div id="carouselExampleControls" class="carousel slide bg-dark" data-bs-ride="carousel">
    <!-- inner -->
    <div class="carousel-inner">
      <!-- 1 -->
      <div class="carousel-item active">
        <img src="{% static 'images/carousel4.jpg' %}" class="d-block w-100 opacity-50" alt="...">
        <div class="carousel-caption">
          <h2 class="fw-bold">세계의 영화를 한곳에.</h2>
          <p>모든 영화들이 이곳에 있습니다</p>
        </div>
      </div>
      <!-- 2 -->
      <div class="carousel-item">
        <img src="{% static 'images/carousel3.jpg' %}" class="d-block w-100 opacity-50" alt="...">
        <div class="carousel-caption">
          <h2 class="fw-bold">당신의 취향에 맞는<br>시리즈 추천.</h2>
          <p></p>
        </div>
      </div>
      <!-- 3 -->
      <div class="carousel-item">
        <img src="{% static 'images/carousel1.jpg' %}" class="d-block w-100 opacity-50" alt="...">
        <div class="carousel-caption">
          <h2 class="fw-bold">다양한 영화 리뷰를 하나로.</h2>
          <p>다양한 유저들과 소통하고 평점을 매겨보세요</p>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

  <!-- 포스터 섹션 -->
  <section class="py-5 px-5">
    <div class="text-center mb-5">
      <h2 class="fw-bold">Boxoffice</h2>
    </div>
    <div class="row row-cols-lg-3 row-cols-md-2 row-cols-sm-1 row-cols-xs-1 gx-4">
      <div class="col mb-5">
        <div class="card h-100">
          <a href="https://www.themoviedb.org/movie/278-the-shawshank-redemption?language=ko"><img class="card-img-top" src="{% static 'images/movie1.jpg' %}" alt="..."/></a>
          <div class="card-body py-4">
            <div class="text-center">
              <h5 class="fw-bold">쇼생크 탈출</h5>
            </div>
            <p class="d-flex justify-content-center mb-0">평점 : 9.88
            </p>
            <div class="d-flex justify-content-center text-warning mb-2">
              <div class="bi-star-fill"></div>
              <div class="bi-star-fill"></div>
              <div class="bi-star-fill"></div>
              <div class="bi-star-fill"></div>
              <div class="bi-star-fill"></div>
            </div>
          </div>
          <div class="card-footer bg-light p-4 pt-0 border-top-0 bg-transparent">
            <div class="text-center">
              <a class="btn btn-outline-dark" href="http://www.cgv.co.kr/ticket/">지금 예매하기</a>
            </div>
          </div>
        </div>
      </div>
      <div class="col mb-5">
        <div class="card h-100">
          <a href="https://www.themoviedb.org/movie/207-dead-poets-society?language=ko"><img class="card-img-top" src="{% static 'images/movie2.jpg' %}" alt="..."/></a>
          <div class="card-body py-4">
            <div class="text-center">
              <h5 class="fw-bold">죽은 시인의 사회</h5>
              <p class="d-flex justify-content-center mb-0">평점 : 9.56
              </p>
              <div class="d-flex justify-content-center text-warning mb-2">
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
              </div>
            </div>
          </div>
          <div class="card-footer bg-light p-4 pt-0 border-top-0 bg-transparent">
            <div class="text-center">
              <a class="btn btn-outline-dark" href="http://www.cgv.co.kr/ticket/">지금 예매하기</a>
            </div>
          </div>
        </div>
      </div>
      <div class="col mb-5">
        <div class="card h-100">
          <a href="https://www.themoviedb.org/movie/49026-the-dark-knight-rises?language=ko"><img class="card-img-top" src="{% static 'images/movie3.jpg' %}" alt="..."/></a>
          <div class="card-body py-4">
            <div class="text-center">
              <h5 class="fw-bold">다크 나이트 라이즈</h5>
              <p class="d-flex justify-content-center mb-0">평점 : 9.56
              </p>
              <div class="d-flex justify-content-center text-warning mb-2">
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
              </div>
            </div>
          </div>
          <div class="card-footer bg-light p-4 pt-0 border-top-0 bg-transparent">
            <div class="text-center">
              <a class="btn btn-outline-dark" href="http://www.cgv.co.kr/ticket/">지금 예매하기</a>
            </div>
          </div>
        </div>
      </div>
      <div class="col mb-5">
        <div class="card h-100">
          <a href="https://www.themoviedb.org/movie/120467-the-grand-budapest-hotel?language=ko"><img class="card-img-top" src="{% static 'images/movie4.jpg' %}" alt="..."/></a>
          <div class="card-body py-4">
            <div class="text-center">
              <h5 class="fw-bold">그랜드 부다페스트 호텔</h5>
              <p class="d-flex justify-content-center mb-0">평점 : 8.71
              </p>
              <div class="d-flex justify-content-center text-warning mb-2">
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
                <div class="bi-star-half"></div>
              </div>
            </div>
          </div>
          <div class="card-footer bg-light p-4 pt-0 border-top-0 bg-transparent">
            <div class="text-center">
              <a class="btn btn-outline-dark" href="http://www.cgv.co.kr/ticket/">지금 예매하기</a>
            </div>
          </div>
        </div>
      </div>
      <div class="col mb-5">
        <div class="card h-100">
          <a href="https://www.themoviedb.org/movie/152601-her?language=ko"><img class="card-img-top" src="{% static 'images/movie5.jpg' %}" alt="..."/></a>
          <div class="card-body py-4">
            <div class="text-center">
              <h5 class="fw-bold">그녀</h5>
              <p class="d-flex justify-content-center mb-0">평점 : 8.70
              </p>
              <div class="d-flex justify-content-center text-warning mb-2">
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
                <div class="bi-star-half"></div>
              </div>
            </div>
          </div>
          <div class="card-footer bg-light p-4 pt-0 border-top-0 bg-transparent">
            <div class="text-center">
              <a class="btn btn-outline-dark" href="http://www.cgv.co.kr/ticket/">지금 예매하기</a>
            </div>
          </div>
        </div>
      </div>
      <div class="col mb-5">
        <div class="card h-100">
          <a href="https://www.themoviedb.org/movie/316029-the-greatest-showman?language=ko"><img class="card-img-top" src="{% static 'images/movie6.jpg' %}" alt="..."/></a>
          <div class="card-body py-4">
            <div class="text-center">
              <h5 class="fw-bold">위대한 쇼맨</h5>
              <p class="d-flex justify-content-center mb-0">평점 : 9.31
              </p>
              <div class="d-flex justify-content-center text-warning mb-2">
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
              </div>
            </div>
          </div>
          <div class="card-footer bg-light p-4 pt-0 border-top-0 bg-transparent">
            <div class="text-center">
              <a class="btn btn-outline-dark" href="http://www.cgv.co.kr/ticket/">지금 예매하기</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

Django/Django_실습/20221007_프로젝트-영화 리뷰채널 연결/movpjt/movie/templates/movie/update.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block css %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block body %}
  <div class="container mt-3">
    <h1>수정하기</h1>
    <form action="" method="POST">
      {% csrf_token %}
      {{ review_form.as_p }}
      <button type="submit" class="btn btn-outline-primary">수정</button>
    </form>
  </div>
{% endblock %}

Django/Django_실습/20221007_프로젝트-영화 리뷰채널 연결/movpjt/movpjt/templates/base.html
{% load django_bootstrap5 %}
{% load static %}

<!DOCTYPE html>
<html lang="ko">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BobMovie</title>
    <style>
      @font-face {
        font-family: "NetflixSans";
        src: url("fonts/NetflixSans-Regular.woff2") format("woff2");
        font-weight: normal;
        font-style: normal;
      }

      * {
        font-family: 'NetflixSans';
      }

      .nav-logo {
        width: 5rem;
        object-fit: cover;
      }

      a {
        text-decoration: none;
        color: inherit;
      }
    </style>
    {% bootstrap_css %}
    {% block css %}
      <link rel="stylesheet" href="{% static 'css/movie.css' %}">
    {% endblock css %}

  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="nav mx-1">
        <a href="{% url 'movie:index' %}"><img class="nav-logo mx-1" src="https://user-images.githubusercontent.com/66688033/193211411-15f19a4c-d81f-409c-955a-ec224c8671be.png"/></a>
      </div>
      <button class="navbar-toggler mx-3" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <!-- 두 항목을 오른쪽으로 밀기 .me-auto -->
        <!-- .navbar-nav으로 full-height와 보다 가벼운 네비게이션(드롭다운을 위한 지원 포함)을 실현. -->
        <ul class="navbar-nav mb-2 mx-3 mb-lg-0 ms-lg-4 align-items-end">
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'movie:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'movie:home' %}">Community</a>
          </li>
          <li class="nav-item">
            <a class='nav-link' href="#" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@mdo">Login</a>
          </li>
        </ul>
      </div>

      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <form>
                <div class="mb-3">
                  <label for="email-address" class="col-form-label">Email address</label>
                  <input type="text" class="form-control" id="email-address">
                  <p class="text-black-50">We'll never share your email with anyone else.</p>
                </div>
                <div class="mb-3">
                  <label for="password" class="col-form-label">Password</label>
                  <input type="text" class="form-control" id="password">
                </div>
                <div class="form-check mb-3">
                  <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
                  <label class="form-check-label" for="defaultCheck1">
                    Check me out
                  </label>
                </div>
              </form>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <button type="button" class="btn btn-primary">Submit</button>
            </div>
          </div>
        </div>
      </div>
    </nav>
    {% block body %}{% endblock body %}
    <footer class="py-3 bg-dark col-12 position-fixed bottom-0">
      <div class="container px-4 px-lg-5">
        <p class="m-0 text-center text-white">Web Bootstrap PROJ. by 최준혁</p>
      </div>
    </footer>
    {% bootstrap_javascript %}
  </body>

</html>