Django/Django_실습/20221012_실습-로그인, 로그아웃/authpjt/authapp/urls.py
from django.urls import path 
from . import views

app_name = 'authapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('accounts/', views.accounts, name='accounts'),
    path('detail/<int:pk>', views.detail, name='detail'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

Django/Django_실습/20221012_실습-로그인, 로그아웃/authpjt/authpjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authapp.urls')),
]

Django/Django_실습/20221012_실습-로그인, 로그아웃/authpjt/authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

Django/Django_실습/20221012_실습-로그인, 로그아웃/authpjt/authapp/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'password1', 'password2')

Django/Django_실습/20221012_실습-로그인, 로그아웃/authpjt/authapp/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout

# Create your views here.
def index(request):
    return render(request, 'authapp/index.html')

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('authapp:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form
    }
    return render(request, 'authapp/signup.html', context)

def accounts(request):
    accounts = get_user_model().objects.order_by('-pk')
    context = {
        'accounts': accounts
    }
    return render(request, 'authapp/accounts.html', context)


def detail(request, pk):
  # 유저를 참조할땐 상속을 받고있기때문에 get_user_model을 import 해서 함수로 참조
  user = get_user_model().objects.get(pk=pk)
  context = {
    'user': user
    }
  return render(request, 'authapp/detail.html', context)

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('authapp:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'authapp/login.html', context)


def logout(request):
  auth_logout(request)
  return redirect('authapp:index')

Django/Django_실습/20221012_실습-로그인, 로그아웃/authpjt/authpjt/templates/base.html
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="ko">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% bootstrap_css %}
    {% block css %}{% endblock css %}
  </head>

  <body>
    {% if request.user.is_authenticated %}
      <span>{{ request.user }}님, 환영합니다.</span>
      <a href="{% url 'authapp:logout' %}">로그아웃</a>
    {% else %}
      <span>로그인해주세요.</span>
    {% endif %}
    <div class="container">
      {% block body %}{% endblock body %}
    </div>
    {% bootstrap_javascript %}
  </body>

</html>